wip

diff --git a/.github/workflows/merge-on-label.yml b/.github/workflows/merge-on-label.yml
--- a/.github/workflows/merge-on-label.yml
+++ b/.github/workflows/merge-on-label.yml
@@ -1,11 +1,14 @@
+# Automatically merge PR using rebase if it contains a `auto-merge` label
+# This workflow is necessary to maintain commits hashes and to have a linear history between branches.
+
 name: Merge on label
 on:
   pull_request:
-    types: [labeled]
+    types: [labeled, opened]
 jobs:
   merge:
-    name: Merge if labelled
-    if: ${{ github.event.label.name == 'auto-merge' }}
+    name: Merge
+    if: ${{ contains(github.event.pull_request.labels.*.name, 'auto-merge') && github.event.pull_request.state == 'open' }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the latest code
@@ -16,7 +19,15 @@ jobs:
           set -euo pipefail
           TARGET_BRANCH=${{ github.event.pull_request.base.ref }}
           SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}
-          echo "Merge $SOURCE_BRANCH into $TARGET_BRANCH"
+          # Ensure to merge correct branches (develop->staging->prod)
+          if [ "$TARGET_BRANCH" == "staging" ] && [ "$SOURCE_BRANCH" == "develop" ]; then
+            echo "Merging $SOURCE_BRANCH into $TARGET_BRANCH ..."
+          elif [ "$TARGET_BRANCH" == "prod" ] && [ "$SOURCE_BRANCH" == "staging" ]; then
+            echo "Merging $SOURCE_BRANCH into $TARGET_BRANCH ..."
+          else
+            echo "Cannot automatically merge $SOURCE_BRANCH into $TARGET_BRANCH"
+            exit 1
+          fi
 
           # make sure branches are up-to-date
           git fetch origin $TARGET_BRANCH
@@ -24,6 +35,4 @@ jobs:
           # do the merge with rebase
           git checkout $TARGET_BRANCH
           git pull --rebase origin $SOURCE_BRANCH
-
-          # push back
-          git push --force-with-lease
+          git push
